### ISSUE TITLE
Move Block Sequence not working right

### ISSUE THREAD

**Issue by chilfang** [VazkiiMods/Psi#690]
# Version Information
Forge version: 36.1.0
Psi version: 1.16-93

Trick: Move Block Sequence doesn't seem to work on certain blocks, it looks like it's mainly blocks that are mined with pickaxes but dunno how snow fits into that.

I tested a few blocks and these are the results

Blocks affected: 
Log, Dirt (All variations), Noteblock, Planks, Glass, Ice (All variations), Haybale, Large Mushroom blocks, Glowstone

Blocks not affected: 
Iron Blocks, Piston, Cobblestone, Nylium, Ore, Snow Block, Sandstone, Endstone

**Comment by blaynemm** [comment]
Can confirm. Can't add much more information, but I can confirm it,
