### ISSUE TITLE
Spin Chamber with negative input can spin to the special empty tool slots

### ISSUE THREAD

**Issue by gdavid04** [VazkiiMods/Psi#746]
Steps to reproduce:
- Make a spell that executes Trick: Spin Chamber with input -1
- Put it in the first slot of Psimetal Leggings
- Put on the Psimetal Leggings

What I expected to happen:
The third slot is selected after the spell executes.

What happened instead:
The special always empty slot is selected instead.

This only happens when the input of Trick: Spin Chamber is negative. Putting the spell in the last slot and inputting 1 to Trick: Spin Chamber correctly switches to the first slot.

**Comment by gdavid04** [comment]
Break Loop already deselects the spell, making Spin Chamber wrap around instead would be much more useful.

**Comment by gdavid04** [comment]
Positive and negative inputs having different results is still a bug.

**Comment by Kamefrede** [comment]
After thinking about it I'll change it so it wraps around
