### ISSUE TITLE
[COMPADABILITY], [BALANS]
CAD is too powerfull with The Twilght Forest mod

### ISSUE THREAD

**Issue by User-green** [VazkiiMods/Psi#757]
I think, that CAD can seriusly brack balans if PSI is used with The Twilght Forest:

- Usage of the "Breack block" trick in the Minutaur maze dangeoun — Spell allows to brake walls of the maze too fast (usualy braking one maze block requires 10-15 seconds with efficiency 5 diamond pick, but spell does it instantly). To solve this "mineing time" (like with normal pick) can be added to "Breack block" trick for touth blocks. 
- Usage of the "Smite" trick to fight boses — Allows to wall youself with blocks and slowly wear down bosses remotly. Solution: Caster (or projectile/granade/mine/charge) must see the target to use the "smite" trick. Same should be done for "Explode" and all effects-tricks.To balans this added weekneses — make all effected spells cost less. 

[Issue on the TF github](https://github.com/TeamTwilight/twilightforest/issues/1425)

**Comment by Kamefrede** [comment]
What's Twilight Forest?

**Comment by User-green** [comment]
> What's Twilight Forest?

Mod. https://github.com/TeamTwilight/twilightforest

**Comment by User-green** [comment]
The Twilight Team will not bother with balansing.
