### ISSUE TITLE
Spell Selection Radial instantly closes itself when trying to select a spell, when Psi key bound to mouse side buttons

### ISSUE THREAD

**Issue by Shahelion** [VazkiiMods/Psi#759]
# Version Information
Forge version: 36.2.20
Psi version: 1.16-97

# Further Information
Steps to reproduce:
1. Make a focusing rod
2. Use the Psi keybind to try and open the radial menu. 

What I expected to happen:
It would stay open for longer than 1/10 of a second

What happened instead:
It instantly closes itself. If I am very fast I can select a spell still, but it definitely isn't supposed to do this.

**Comment by Zsashas** [comment]
Followup information: changing the keybind to F fixed it. It was previously set to Mouse 4 (the thumb side buttons). The mouse buttons had previously worked, no idea why it no longer does so.

**Comment by Ramiels** [comment]
to add to this; **all** mouse buttons open the GUI for a moment before cancelling even when the key is held, unlike binding walk forwards to a mouse key
