### ISSUE TITLE
Dont have Key for switch spells

### ISSUE THREAD

**Issue by murilobarbosa2002** [VazkiiMods/Psi#760]
I dont have any Key for switch spells, and dont have a possibility to enter a new hotkey in settings - controls

**Comment by murilobarbosa2002** [comment]
1.16.5
Forge 36.2.22
Psi 1.16-97

**Comment by Ramiels** [comment]
Do you have "Psi Master Keybind" under inventory? It's the same key used for opening the Encyclopaedia Psionica while holding a CAD or other spell bullet-holding item

**Comment by Kamefrede** [comment]
The default key should be C, unless the modpack you're playing in changed it! 
You can find it under the inventory category with the name "Psi Master Keybind"
