### ISSUE TITLE
Crash in ATM6 when picking up CAD Assemblies with CAD Assembler GUI open.

### ISSUE THREAD

**Issue by AlfarelSynthesis** [VazkiiMods/Psi#765]
# Version Information
Forge version: 36.2.34
Psi version: Psi 1.16-97.jar

# Further Information
Link to crash log: https://www.toptal.com/developers/hastebin/oqoquxohor.rb

Steps to reproduce:
1. Craft or give yourself a CAD Assembly. Tested with gold and iron.
2. Place CAD Assembler.
3. Open CAD Assembler GUI, and click on an assembly in order to pick it up.
4. Crash.

What I expected to happen: Ability to use assembly, without crashes.

What happened instead: Crash,

Side note: This is honestly probably something going wrong with ATM6, or similar, but I can't seem to figure it out, so I figured I may as well semi-ask for help here.

**Comment by AlfarelSynthesis** [comment]
To specify, I mean pick up with mouse, not off the ground.

**Comment by ArchEzekiel** [comment]
+1
I'm having this exact same issue as well, in a different modpack

**Comment by Kamefrede** [comment]
Closing this as it seems to be fixed on newer versions and we don't have enough people to maintain older versions.
