### ISSUE TITLE
DIE does not stop PSI consumption 

### ISSUE THREAD

**Issue by ContestMath** [VazkiiMods/Psi#766]
Psi version: 1.16-97

It pretty much is what the title suggests: When I cast any spell, which then dies the PSI is consumed anyways.

**Comment by gdavid04** [comment]
Working as intended. Spells have fixed cost deduced on cast before any tricks execute by design. Trick: Spin Chamber in loopcast or armor can be used to effectively stop the spell from depleting your psi unless a condition is met.

**Comment by ContestMath** [comment]
Thank you very much for the reply! I am sorry that I did not put enough
research into the topic.
