### ISSUE TITLE
[REQUEST] Json recipe support

### ISSUE THREAD

**Issue by th3impasta** [VazkiiMods/Psi#782]
Hello. I am working on a modpack. I would like this mod to add Json or crafttweaker support so I can make this mod an integral part of my modpack.

**Comment by Kamefrede** [comment]
Psi already supports JSON recipes for the only new kind of recipe it adds, infusions
Example:
https://github.com/VazkiiMods/Psi/blob/master/src/generated/resources/data/psi/recipes/ebony_substance.json
