### ISSUE TITLE
1.19: Spamless debug tricks are missing

### ISSUE THREAD

**Issue by Vazkii** [VazkiiMods/Psi#786]

**Comment by panda885** [comment]
Note: They're not missing, they're just defaulted to the behavior of a normal debug trick: https://github.com/VazkiiMods/Psi/blob/4f3d49a780bfe9ea1cc5dac7970c3df8bd7dfe9f/src/main/java/vazkii/psi/common/network/message/MessageSpamlessChat.java#L43
