### ISSUE TITLE
All Achievements unlocked after punching a tree?

### ISSUE THREAD

**Issue by MrBobbyMan** [VazkiiMods/Psi#790]
# Version Information
Forge version: 40.2.2
Psi version: 1.18.2

# Further Information
Not much to say here, just collect a log, and you're done.

**Comment by KnifeOfDunwall** [comment]
I have the same issue but it was different in every world. in one it was getting wood, in another one it was just opening the inventory

**Comment by MrBobbyMan** [comment]
If that's the case, it may be when you get ANY achievement.

**Comment by gdavid04** [comment]
It might be the case, I got all advancements after first using a Spell Programmer.
