### ISSUE TITLE
Texture Issues in 1.19

### ISSUE THREAD

**Issue by KnifeOfDunwall** [VazkiiMods/Psi#791]
last i have played was 1.12 with stoneblock where the strip on the side had your psi colors but in this version it is white. since i have not played that long i am unsure wether this is indeed a bug or a feature. On the ivory CAD there is a small pink Slither that is untextured/has a missing texture.
![image](https://user-images.githubusercontent.com/63566078/234725526-705550d0-5429-4a49-81b1-605225744831.png)

**Comment by KnifeOfDunwall** [comment]
also the backside texture of the cad assembler and programmer "despawns" when a few blocks away

**Comment by panda885** [comment]
What mods are you using with Psi?

Could be a compatibility issue with [the Oculus mod](https://modrinth.com/mod/oculus), works fine for me with the mod standalone. I also noticed this issue in my modpack, fixed by removing Oculus completely.

**Comment by KnifeOfDunwall** [comment]
Yeah, oculus should be in the Pack. I just added psi to atm8. Is there any workaround since i use shaders?

**Comment by TheFurryDevil** [comment]
Disable Block Face Culling in the video settings. Or make a tiny resource pack that disables it for that block only, not tested tho.

**Comment by Kamefrede** [comment]
Fixed in 9458736?
