### ISSUE TITLE
(Multiplayer) Energy bar capacity/regen rate desync

### ISSUE THREAD

**Issue by Numilani** [VazkiiMods/Psi#794]
# Version Information
Forge version: 1.18.2 40.2.0
Psi version: 1.18.2-98

# Further Information
Steps to reproduce:
1. Craft and cast a spell that consumes psi energy on a multiplayer server.
2. Cast a spell to bring the energy bar down from max.

What I expected to happen:
The regen value should stay constant, and the bar should slowly refill.

What happened instead:
The bar never refills, and the regen value rapidly flickers between 0 and 12.

I assume this is similar to #552 but it occurs only on multiplayer servers, and it's not on Sponge - this is a regular Forge server.

**Comment by panda885** [comment]
Looks like I already fixed the issue in the 1.19.2 port, going to try to cherry pick the changes.

**Comment by Xplodin** [comment]
this still occurs in 1.18.2
