### ISSUE TITLE
Unable to play on M1 macOS

### ISSUE THREAD

**Issue by david675566** [VazkiiMods/Psi#799]
# Version Information
Forge version: 40.2.14
Psi version: 2.0.0

# Further Information
Link to crash log: [mclo link](https://mclo.gs/ng5kLv6)
Steps to reproduce:

1. Download and install on a M1 Mac system.
2. Startup with Psi mod installed.

What I expected to happen:
Startup and initialized successfully. Able to play.

What happened instead:
Crashed on startup up/Forge initialization.

Currently installed Java 17, seems related to OpenGL context window declare issue stated in the provided log at Line 2068.

**Comment by williewillus** [comment]
This whole file https://github.com/VazkiiMods/Psi/blob/master/src/main/java/vazkii/psi/client/core/handler/ShaderHandler.java

needs to be modernized to use the API's vanilla uses, it doesn't look like it's been updated since 2016. On M1, the ARB extensions that it's using probably don't exist.

**Comment by Kamefrede** [comment]
Should be fixed in `1.19-101`, although I don't have a mac so expectations may not correspond to reality

**Comment by david675566** [comment]
Hi, thanks for the fix and sorry been this late and I had to reopen this issue.

As I fired up today, the Minecraft on my M1 mac will not straight up crashed into oblivion,
confirmed the OpenGL context now solved,
but now still refuse to play as the other issue either SoundEvent or ResourceLocation method is at fault in this file: [https://github.com/VazkiiMods/Psi/blob/master/src/main/java/vazkii/psi/common/core/handler/PsiSoundHandler.java](https://github.com/VazkiiMods/Psi/blob/master/src/main/java/vazkii/psi/common/core/handler/PsiSoundHandler.java)

Log file: https://mclo.gs/hisYx9w (at Line 168)

I'm currently looking at the file as well, tho I'm not experienced in both M1 infrastructure & java/forge API so probably not able to come up a solution.

**Comment by Kamefrede** [comment]
That should be fixed as well, what version are you using?

**Comment by david675566** [comment]
> That should be fixed as well, what version are you using?

Java 17
Minecraft 1.19.4
Psi 1.19-101 download from [Modrinth](https://modrinth.com/mod/psi/version/1.19-101)
