### ISSUE TITLE
Psi crashing a server because of net.minecraft.resources.ResourceLocation net.minecraft.sounds.SoundEvent.getLocation()

### ISSUE THREAD

**Issue by Acrimoris** [VazkiiMods/Psi#800]
# Version Information
Forge version: 1.19.2 - 43.3.0 and 1.19.2 - 43.3.5

# Further Information
Link to crash log: https://gist.github.com/Acrimoris/1a1591eaf35d39d45420260192f86f3f
Steps to reproduce:
1. Create server Forge 1.19.2 with Psi and Patchouli
2. Run the server

What I expected to happen:
Server starting normally and creating a world.

What happened instead:
Server didn't start normally and failed to generate a world.

**Comment by Kamefrede** [comment]
Fixed in version `1.19-100`
